/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import kontrolor.Kontroler;
import model.Adresa;
import model.Ulica;
import model.UlicaBroj;
import modelitabela.ModelTabeleAdresa;
import modelitabela.ModelTabeleAdresaII;

/**
 *
 * @author Dell
 */
public class FIzmeniUlicu extends javax.swing.JFrame {

    /**
     * Creates new form FIzmeniUlicu
     */
    ModelTabeleAdresaII mta;
    Ulica ulica;

    public FIzmeniUlicu() {
        initComponents();

    }

    FIzmeniUlicu(Ulica ulica) {
        initComponents();
        this.ulica = ulica;
        mta = new ModelTabeleAdresaII();
        jtblAdresa.setModel(mta);
        srediTabelu(ulica);
        jtxtNazivUlice.setText(ulica.getNazivUlice());
        jtxtNazivMesta.setText(ulica.getNazivMesta());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAdresa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtNazivUlice = new javax.swing.JTextField();
        jtxtNazivMesta = new javax.swing.JTextField();
        jbtnDodajAdresu = new javax.swing.JButton();
        jbtnObrisiAdresu = new javax.swing.JButton();
        jbtnIzmeni = new javax.swing.JButton();
        jbtnIzmeniAdresu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtblAdresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblAdresa);

        jLabel1.setText("Naziv ulice:");

        jLabel2.setText("Naziv mesta:");

        jbtnDodajAdresu.setText("Dodaj adresu");
        jbtnDodajAdresu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajAdresuActionPerformed(evt);
            }
        });

        jbtnObrisiAdresu.setText("Obrisi adresu");
        jbtnObrisiAdresu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiAdresuActionPerformed(evt);
            }
        });

        jbtnIzmeni.setText("Izmeni ulicu");
        jbtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniActionPerformed(evt);
            }
        });

        jbtnIzmeniAdresu.setText("Izmeni adresu");
        jbtnIzmeniAdresu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniAdresuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtxtNazivUlice))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtxtNazivMesta)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnDodajAdresu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jbtnObrisiAdresu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jbtnIzmeniAdresu, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNazivUlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNazivMesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodajAdresu)
                    .addComponent(jbtnObrisiAdresu)
                    .addComponent(jbtnIzmeniAdresu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnIzmeni)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnObrisiAdresuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiAdresuActionPerformed

        int red = jtblAdresa.getSelectedRow();
        if (red != -1) {

            mta = (ModelTabeleAdresaII) jtblAdresa.getModel();
            mta.obrisiAdresu(red);

        } else {

            JOptionPane.showMessageDialog(this, "Niste izabrali adresu koju zelite da obrisete");
            return;
        }


    }//GEN-LAST:event_jbtnObrisiAdresuActionPerformed

    private void jbtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniActionPerformed

        String nazivUlice = jtxtNazivUlice.getText();
        String nazivMesta = jtxtNazivMesta.getText();
        mta = (ModelTabeleAdresaII) jtblAdresa.getModel();
        ArrayList<Adresa> adrese = mta.vratiSveAdrese();
        String dodatak = "";

        Ulica u = new Ulica(ulica.getUlicaID(), nazivUlice, nazivMesta, adrese, ulica.getMesto(), "update");
        if (!nazivMesta.equals(ulica.getNazivMesta())) {
            dodatak = ", nazivmesta='" + u.getNazivMesta() + "'";

        }
        Kontroler.getInstanca().izmeniUlicu(u, dodatak);


    }//GEN-LAST:event_jbtnIzmeniActionPerformed

    private void jbtnDodajAdresuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajAdresuActionPerformed
        FKreirajAdresu fda = new FKreirajAdresu(this, true);
        fda.pack();
        fda.setVisible(true);
    }//GEN-LAST:event_jbtnDodajAdresuActionPerformed

    private void jbtnIzmeniAdresuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniAdresuActionPerformed

        int red = jtblAdresa.getSelectedRow();
        if (red != -1) {
            mta = (ModelTabeleAdresaII) jtblAdresa.getModel();
            Adresa a=mta.vratiAdresu(red);
            int broj=Integer.parseInt(JOptionPane.showInputDialog("Unesite broj"));
            String dodatakBroju=JOptionPane.showInputDialog("Unesite dodatak broju");
            UlicaBroj ulicaBroj=new UlicaBroj("MARIJA.ULICA_BROJ", broj, dodatakBroju);
            
            mta.setValueAt(broj, red, 0);
            mta.setValueAt(dodatakBroju, red, 1);
            
            
            Adresa izmenjena=new Adresa(a.getAdresaID(), ulicaBroj, ulica,"update");
            mta.izmeni(red, izmenjena);
            
          
        } else {

            JOptionPane.showMessageDialog(this, "Niste izabrali adresu koju zelite da izmenite");
            return;

        }


    }//GEN-LAST:event_jbtnIzmeniAdresuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIzmeniUlicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIzmeniUlicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIzmeniUlicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIzmeniUlicu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FIzmeniUlicu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodajAdresu;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnIzmeniAdresu;
    private javax.swing.JButton jbtnObrisiAdresu;
    private javax.swing.JTable jtblAdresa;
    private javax.swing.JTextField jtxtNazivMesta;
    private javax.swing.JTextField jtxtNazivUlice;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void srediTabelu(Ulica ulica) {

        ArrayList<Adresa> lista = kontrolor.Kontroler.getInstanca().vratiAdreseZaUlicu(ulica);
        mta = (ModelTabeleAdresaII) jtblAdresa.getModel();
        mta.setLista(lista);

    }

    void dodajAdresu(int adresaID, int broj, String dodatakBroju) {
        UlicaBroj ulicaBroj = new UlicaBroj("MARIJA.ULICA_BROJ", broj, dodatakBroju);
        Adresa adresa = new Adresa(adresaID, ulicaBroj, ulica, "insert");
        mta = (ModelTabeleAdresaII) jtblAdresa.getModel();
        mta.dodajAdresu(adresa);

    }

    void izmeniAdresu(Adresa adresa) {

        int red = jtblAdresa.getSelectedRow();
        mta=(ModelTabeleAdresaII)jtblAdresa.getModel();
        mta.izmeni(red,adresa);

    }
}
