/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import kontrolor.Kontroler;
import model.Artikal;
import model.Cena;
import modelitabela.ModelTabeleArtikal;
import modelitabela.ModelTabeleCena;

/**
 *
 * @author Dell
 */
public class FIzmeniArtikal extends javax.swing.JFrame {

    ModelTabeleCena mtc;
    Artikal a;
    Cena c;

    /**
     * Creates new form FIzmeniArtikal
     */
    FIzmeniArtikal(Artikal a) {
        initComponents();
        mtc = new ModelTabeleCena();
        jtblCena.setModel(mtc);
        this.a = a;
        srediFormu();
        srediTabelu();

    }

    public FIzmeniArtikal() {
    }

    FIzmeniArtikal(Cena c) {
        initComponents();
        mtc = new ModelTabeleCena();
        jtblCena.setModel(mtc);
//        srediTabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtIdArtikla = new javax.swing.JTextField();
        jtxtNaziv = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtOpis = new javax.swing.JTextArea();
        jbtnDodajCenu = new javax.swing.JButton();
        jbtnObrisiCenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCena = new javax.swing.JTable();
        jbtnIzmeniArtikal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtxtAktuelnaCena = new javax.swing.JTextField();
        jbtnIzmeniCenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID artikla:");

        jLabel2.setText("Naziv artikla:");

        jLabel3.setText("Opis artikla:");

        jtxtIdArtikla.setEditable(false);

        jtxtOpis.setColumns(20);
        jtxtOpis.setRows(5);
        jScrollPane2.setViewportView(jtxtOpis);

        jbtnDodajCenu.setText("Dodaj cenu");
        jbtnDodajCenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajCenuActionPerformed(evt);
            }
        });

        jbtnObrisiCenu.setText("Obrisi cenu");
        jbtnObrisiCenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiCenuActionPerformed(evt);
            }
        });

        jtblCena.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblCena);

        jbtnIzmeniArtikal.setText("Izmeni artikal");
        jbtnIzmeniArtikal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniArtikalActionPerformed(evt);
            }
        });

        jLabel4.setText("Aktuelna cena:");

        jbtnIzmeniCenu.setText("Izmeni cenu");
        jbtnIzmeniCenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniCenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnIzmeniArtikal, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jtxtIdArtikla))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnDodajCenu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnObrisiCenu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jbtnIzmeniCenu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2)
                            .addComponent(jtxtNaziv)
                            .addComponent(jtxtAktuelnaCena))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtIdArtikla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAktuelnaCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodajCenu)
                    .addComponent(jbtnObrisiCenu)
                    .addComponent(jbtnIzmeniCenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnIzmeniArtikal)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajCenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajCenuActionPerformed
        DodajCenu dc = new DodajCenu(this, true);
        dc.pack();
        dc.setVisible(true);

    }//GEN-LAST:event_jbtnDodajCenuActionPerformed

    private void jbtnObrisiCenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiCenuActionPerformed
        int red = jtblCena.getSelectedRow();
        if (red != -1) {

            mtc = (ModelTabeleCena) jtblCena.getModel();
            Cena c = mtc.vratiCenu(red);
            c.setStatus("delete");
            mtc.obrisiCenu(red);

        } else {

            JOptionPane.showMessageDialog(this, "Niste izabrali cenu koju zelite da obrisete");
            return;

        }

    }//GEN-LAST:event_jbtnObrisiCenuActionPerformed

    private void jbtnIzmeniArtikalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniArtikalActionPerformed
        mtc = (ModelTabeleCena) jtblCena.getModel();
        int artikalID = Integer.parseInt(jtxtIdArtikla.getText());
        String nazivArtikla = jtxtNaziv.getText();
        String opisArtikla = jtxtOpis.getText();
        ArrayList<Cena> cene = mtc.vratiSveCene();
        double aktuelnaCena = Double.parseDouble(jtxtAktuelnaCena.getText());

        Artikal artikal = new Artikal(artikalID, nazivArtikla, opisArtikla, cene, aktuelnaCena);
        Kontroler.getInstanca().izmeniArtikal(artikal);

    }//GEN-LAST:event_jbtnIzmeniArtikalActionPerformed

    private void jbtnIzmeniCenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniCenuActionPerformed

        int red = jtblCena.getSelectedRow();
        if (red != -1) {
            mtc = (ModelTabeleCena) jtblCena.getModel();
            Cena cena=mtc.vratiCenu(red);
            double iznos=Double.parseDouble(JOptionPane.showInputDialog("Unesite novi iznos cene:"));
            mtc.setValueAt(iznos, red, 1);
            Cena izmenjena=new Cena(cena.getDatumOd(), iznos, cena.getValuta(), cena.getArtikal(), "update");
            mtc.izmeniCenu(izmenjena, red);

        } else {
            JOptionPane.showMessageDialog(this, "Niste izabrali cenu koju zelite da izmenite");
            return;

        }


    }//GEN-LAST:event_jbtnIzmeniCenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIzmeniArtikal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIzmeniArtikal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIzmeniArtikal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIzmeniArtikal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FIzmeniArtikal forma = new FIzmeniArtikal();
                forma.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                forma.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnDodajCenu;
    private javax.swing.JButton jbtnIzmeniArtikal;
    private javax.swing.JButton jbtnIzmeniCenu;
    private javax.swing.JButton jbtnObrisiCenu;
    private javax.swing.JTable jtblCena;
    private javax.swing.JTextField jtxtAktuelnaCena;
    private javax.swing.JTextField jtxtIdArtikla;
    private javax.swing.JTextField jtxtNaziv;
    private javax.swing.JTextArea jtxtOpis;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {

        jtxtIdArtikla.setText(a.getArtikalID() + "");
        jtxtNaziv.setText(a.getNazivArtikla());
        jtxtOpis.setText(a.getOpisArtikla());
        jtxtAktuelnaCena.setText(a.getAktuelnaCena() + "");

    }

    private void srediTabelu() {

        ArrayList<Cena> cene = Kontroler.getInstanca().vratiCeneZaArtikal(a);
        mtc = (ModelTabeleCena) jtblCena.getModel();
        mtc.setLista(cene);
    }

    public void dodajCenu(Cena cena) {
        mtc = (ModelTabeleCena) jtblCena.getModel();
        mtc.dodajCenu(cena);
    }

}
